- name: Useradd
  user:
    name: "{{ item.key }}"
    group: "{{ item.value.group }}"
    generate_ssh_key: yes
    home: "/home/{{ item.key }}"
    shell: "{{ '/bin/bash' if item.value.ssh else '/usr/sbin/nologin' }}"
  loop: "{{ ssh_users | dict2items }}"

- name: Configure SSH authorized_keys
  authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ lookup('file', 'public_keys/' ~ item.key ~ '.key.pub') }}"
    path: "/home/{{ item.key }}/.ssh/authorized_keys"
  loop: "{{ ssh_users | dict2items }}"

- name: Add user to sudo
  lineinfile:
    path: "/etc/sudoers.d/{{ item.key }}"
    line: "{{ item.key }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: "0440"
    create: yes
    validate: "visudo -cf %s"
  loop: "{{ ssh_users | dict2items }}"
  when: item.value.ssh